name = "maxmint"
version = "1.0.0"
description = "OP Mainnet deployment of MaxMint"
include = [
    "common.toml"
]

[setting.addressresolver]
defaultValue = "0x1Cb059b7e74fD21665968C908806143E744D5F30"
