name = "maxmint"
version = "1.0.0"
description = "auto minting function for synthetix v2x with gelato"

[setting.addressresolver]
description = "Synthetix V2X ReadAddressResolver Address"

[contract.maxmint]
artifact = "MaxMint"
args = [
    "<%= settings.addressresolver %>"
]